name: hello world

on:
  push:
   branches:
     - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: action/checkout@v2
      - name: Run a online script
        run: echo hello, world!
        
     
     
    
