name: hello world

on:
  push:
   branches:
     - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run a online script
      run: echo hello, world!
        
     
     
    
